mixed-port: 7890
allow-lan: false
bind-address: '*'
mode: rule
log-level: info
external-controller: '127.0.0.1:9090'
unified-delay: true
tcp-concurrent: true
dns:
  enable: true
  ipv6: false
  default-nameserver: [223.5.5.5, 119.29.29.29, 114.114.114.114]
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  respect-rules: true
  proxy-server-nameserver: [223.5.5.5, 119.29.29.29, 114.114.114.114]
  nameserver: [223.5.5.5, 119.29.29.29, 114.114.114.114]
  fallback: [1.1.1.1, 8.8.8.8]
  fallback-filter:
    geoip: true
    geoip-code: CN
    nameserver-policy: [gfw]
    ipcidr: [240.0.0.0/4]
    domain: [+.google.com, +.facebook.com, +.youtube.com]

rule-providers:
  cloudflare-extra:
    type: http
    behavior: classical
    format: text
    url: https://gh-proxy.org/https://raw.githubusercontent.com/feiyang1128/syncFile/refs/heads/main/Mihomo/file/list/cloudflare-extra.list
    path: ./ruleset/cloudflare-extra.list
    interval: 21600
  direct:
    type: http
    behavior: classical
    format: text
    url: https://gh-proxy.org/https://raw.githubusercontent.com/feiyang1128/syncFile/refs/heads/main/Mihomo/file/list/direct.list
    path: ./ruleset/direct.list
    interval: 21600
  unban:
    type: http
    behavior: classical
    format: text
    url: https://gh-proxy.org/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
    path: ./ruleset/unban.list
    interval: 21600
  reject-extra:
    type: http
    behavior: classical
    format: text
    url: https://gh-proxy.org/https://raw.githubusercontent.com/feiyang1128/syncFile/refs/heads/main/Mihomo/file/list/reject-extra.list
    path: ./ruleset/reject-extra.list
    interval: 21600
  reject-ad:
    type: http
    behavior: classical
    format: text
    url: https://gh-proxy.org/https://raw.githubusercontent.com/feiyang1128/syncFile/refs/heads/main/Mihomo/file/list/reject-ad.list
    path: ./ruleset/reject-ad.list
    interval: 21600
  ai:
    type: http
    behavior: classical
    format: text
    url: https://gh-proxy.org/https://raw.githubusercontent.com/feiyang1128/syncFile/refs/heads/main/Mihomo/file/list/AI.list
    path: ./ruleset/ai.list
    interval: 21600
  cloudflareip:
    type: http
    behavior: classical
    format: text
    url: https://gh-proxy.org/https://raw.githubusercontent.com/feiyang1128/syncFile/refs/heads/main/Mihomo/file/list/cloudflareip.list
    path: ./ruleset/cloudflareip.list
    interval: 21600
  ipv6:
    type: http
    behavior: classical
    format: text
    url: https://gh-proxy.org/https://raw.githubusercontent.com/feiyang1128/syncFile/refs/heads/main/Mihomo/file/list/ipv6.list
    path: ./ruleset/ipv6.list
    interval: 21600
  proxy:
    type: http
    behavior: classical
    format: text
    url: https://gh-proxy.org/https://raw.githubusercontent.com/feiyang1128/syncFile/refs/heads/main/Mihomo/file/list/proxy.list
    path: ./ruleset/proxy.list
    interval: 21600
