[custom]
;不要随意改变关键字，否则会导致出错

;去广告：支持增强拦截
;自动测速：支持
;负载均衡：支持轮询/散列
;AI分流：支持
;Cloudflare分流：支持
;IPV6分流：支持直连兜底
;增强中国IP段：不支持
;增强国外GFW：不支持
;多国家分组：不支持

clash_rule_base=https://gh-proxy.org/https://raw.githubusercontent.com/feiyang1128/syncFile/refs/heads/main/Mihomo/file/base.yml

custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`[]🌐 IPV6`[]DIRECT`[]🔮 负载-轮询`[]🔮 负载-散列`[]🔯 故障转移`^(?!.*(v6|V6|ipv6|IPV6)).*$
custom_proxy_group=♻️ 自动选择`url-test`^(?!.*(v6|V6|ipv6|IPV6)).*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🌐 IPV6`url-test`[]DIRECT`.*`http://[2400:3200::1]`60,,30
custom_proxy_group=✨ AI`url-test`^(?!.*(v6|V6|ipv6|IPV6|香港|HK|台湾|TW|澳门|MO|🇭🇰|🇹🇼|🇲🇴|🇨🇳|套餐|到期|有效|剩余|版本|已用|过期|失联|测试|官方|网址|备用|群|TEST|客服|网站|获取|订阅|流量|机场|下次|官址|联系|邮箱|工单|学术|USE|USED|TOTAL|EXPIRE|EMAIL)).*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🌍 cloudflare`url-test`^(?!.*(v6|V6|ipv6|IPV6|cf|CF|cloudflare|Cloudflare|CLOUDFLARE)).*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🔮 负载-轮询`load-balance`^(?!.*(v6|V6|ipv6|IPV6)).*$`http://www.gstatic.com/generate_204`300
custom_proxy_group=🔮 负载-散列`load-balance`^(?!.*(v6|V6|ipv6|IPV6)).*$`http://www.gstatic.com/generate_204`300
custom_proxy_group=🔯 故障转移`fallback`^(?!.*(v6|V6|ipv6|IPV6)).*$`http://www.gstatic.com/generate_204`300
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择
custom_proxy_group=🛑 全球拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]🎯 全球直连`[]♻️ 自动选择`.*

enable_rule_generator=false
overwrite_original_rules=false
