[custom]
;不要随意改变关键字，否则会导致出错

;去广告：支持增强拦截
;自动测速：支持
;负载均衡：支持轮询/散列
;AI分流：支持
;Cloudflare分流：支持
;IPV6分流：支持直连兜底
;增强中国IP段：不支持
;增强国外GFW：不支持
;多国家分组：不支持

clash_rule_base=https://gh-proxy.org/https://raw.githubusercontent.com/feiyang1128/syncFile/refs/heads/main/Mihomo/file/mihomo_rule_provider_base.yml

enable_rule_generator=false
overwrite_original_rules=false
